In [1]:
import pandas as pd
pd.options.display.max_columns = None
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OrdinalEncoder, PolynomialFeatures
from sklearn.linear_model import LogisticRegression, PassiveAggressiveClassifier, Perceptron, SGDClassifier, RidgeClassifier
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import GridSearchCV, RepeatedStratifiedKFold, cross_val_score, train_test_split, HalvingGridSearchCV
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, GradientBoostingClassifier, HistGradientBoostingClassifier, AdaBoostClassifier, ExtraTreesClassifier, BaggingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.decomposition import PCA

### Preprocessing

In [3]:
df = pd.read_csv('fraudTrain.csv', index_col=0, parse_dates=['trans_date_trans_time'])

Based on discoveries of EDA, I delete some featurs and transform others.

In [6]:
df.rename(columns={'trans_date_trans_time':'time', 'amt':'amount'}, inplace=True)
df['industry_code'] = df['cc_num'].astype(str).apply(lambda x: x[0:1]).astype(int)
df['age'] = (pd.to_datetime('today') - pd.to_datetime(df['dob'])).dt.days/365.25 
df.drop(columns=['first', 'last', 'street', 'trans_num', 'unix_time', 'cc_num', 'dob', 'lat', 'long', 'merch_lat', 'merch_long', 'zip', 'city', 'job', 'merchant'], inplace=True)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns='is_fraud'), df['is_fraud'], test_size=0.25, random_state=1)

In [8]:
X_train['time'] = (X_train['time'] - pd.Timestamp("1970-01-01")) // pd.Timedelta('1s')

X_train_num = X_train.drop(columns=['category', 'gender', 'state'])
X_train_cat = X_train[['category', 'gender', 'state']]

scale before test


2. Transform
3. Test
4. Generate
5. Test
6. Select
7. Test, test learning
8. Imbalance
9. Test, test learning

### Feature generation

In [13]:
pf = PolynomialFeatures(degree=4, include_bias=False)
X_train_num = pd.DataFrame(pf.fit_transform(X_train_num), columns=pf.get_feature_names_out(X_train_num.columns))
X_train_num

,time,amount,city_pop,industry_code,age,time^2,time amount,time city_pop,time industry_code,time age,amount^2,amount city_pop,amount industry_code,amount age,city_pop^2,city_pop industry_code,city_pop age,industry_code^2,industry_code age,age^2,time^3,time^2 amount,time^2 city_pop,time^2 industry_code,time^2 age,time amount^2,time amount city_pop,time amount industry_code,time amount age,time city_pop^2,time city_pop industry_code,time city_pop age,time industry_code^2,time industry_code age,time age^2,amount^3,amount^2 city_pop,amount^2 industry_code,amount^2 age,amount city_pop^2,amount city_pop industry_code,amount city_pop age,amount industry_code^2,amount industry_code age,amount age^2,city_pop^3,city_pop^2 industry_code,city_pop^2 age,city_pop industry_code^2,city_pop industry_code age,city_pop age^2,industry_code^3,industry_code^2 age,industry_code age^2,age^3,time^4,time^3 amount,time^3 city_pop,time^3 industry_code,time^3 age,time^2 amount^2,time^2 amount city_pop,time^2 amount industry_code,time^2 amount age,time^2 city_pop^2,time^2 city_pop industry_code,time^2 city_pop age,time^2 industry_code^2,time^2 industry_code age,time^2 age^2,time amount^3,time amount^2 city_pop,time amount^2 industry_code,time amount^2 age,time amount city_pop^2,time amount city_pop industry_code,time amount city_pop age,time amount industry_code^2,time amount industry_code age,time amount age^2,time city_pop^3,time city_pop^2 industry_code,time city_pop^2 age,time city_pop industry_code^2,time city_pop industry_code age,time city_pop age^2,time industry_code^3,time industry_code^2 age,time industry_code age^2,time age^3,amount^4,amount^3 city_pop,amount^3 industry_code,amount^3 age,amount^2 city_pop^2,amount^2 city_pop industry_code,amount^2 city_pop age,amount^2 industry_code^2,amount^2 industry_code age,amount^2 age^2,amount city_pop^3,amount city_pop^2 industry_code,amount city_pop^2 age,amount city_pop industry_code^2,amount city_pop industry_code age,amount city_pop age^2,amount industry_code^3,amount industry_code^2 age,amount industry_code age^2,amount age^3,city_pop^4,city_pop^3 industry_code,city_pop^3 age,city_pop^2 industry_code^2,city_pop^2 industry_code age,city_pop^2 age^2,city_pop industry_code^3,city_pop industry_code^2 age,city_pop industry_code age^2,city_pop age^3,industry_code^4,industry_code^3 age,industry_code^2 age^2,industry_code age^3,age^4
0,1.553916e+09,61.56,2135.0,4.0,20.501027,2.414656e+18,9.565910e+10,3.317612e+12,6.215666e+09,3.185688e+10,3789.6336,131430.60,246.24,1262.043203,4.558225e+06,8540.0,4.376969e+04,16.0,82.004107,420.292096,3.752174e+27,1.486462e+20,5.155291e+21,9.658625e+18,4.950293e+19,5.888774e+12,2.042322e+14,3.826364e+11,1.961110e+12,7.083101e+15,1.327045e+13,6.801444e+13,2.486266e+10,1.274275e+11,6.530988e+11,2.332898e+05,8.090868e+06,15158.5344,7.769138e+04,2.806043e+08,5.257224e+05,2.694462e+06,984.96,5048.172813,25873.181400,9.731810e+09,1.823290e+07,9.344829e+07,34160.0,1.750788e+05,8.973236e+05,64.0,328.016427,1681.168382,8616.419469,5.830565e+36,2.309838e+29,8.010892e+30,1.500870e+28,7.692342e+28,9.150663e+21,3.173597e+23,5.945850e+20,3.047401e+21,1.100655e+25,2.062116e+22,1.056888e+23,3.863450e+19,1.980117e+20,1.014861e+21,3.625129e+14,1.257253e+16,2.355510e+13,1.207259e+14,4.360357e+17,8.169287e+14,4.186969e+15,1.530546e+12,7.844439e+12,4.020476e+13,1.512242e+19,2.833240e+16,1.452108e+17,5.308179e+13,2.720578e+14,1.394366e+15,9.945065e+10,5.097101e+11,2.612395e+12,1.338920e+13,1.436132e+07,4.980738e+08,9.331594e+05,4.782681e+06,1.727400e+10,3.236347e+07,1.658711e+08,60634.1376,3.107655e+05,1.592753e+06,5.990902e+11,1.122417e+09,5.752677e+09,2.102890e+06,1.077785e+07,5.523924e+07,3939.84,20192.691253,1.034927e+05,5.304268e+05,2.077742e+13,3.892724e+10,1.995121e+11,7.293160e+07,3.737932e+08,1.915786e+09,136640.0,7.003151e+05,3.589294e+06,1.839606e+07,256.0,1312.065708,6724.673528,3.446568e+04,1.766454e+05
1,1.576587e+09,47.43,1263321.0,4.0,65.363450,2.485628e+18,7.477754e+10,1.991736e+15,6.306350e+09,1.030512e+11,2249.6049,59919315.03,189.72,3100.188419,1.595980e+12,5053284.0,8.257502e+07,16.0,261.453799,4272.380556,3.918810e+27,1.178933e+20,3.140146e+24,9.942512e+18,1.624692e+20,3.546699e+12,9.446804e+16,2.991102e+11,4.887718e+12,2.516202e+21,7.966944e+15,1.301867e+17,2.522540e+10,4.122048e+11,6.735782e+12,1.066988e+05,2.841973e+09,8998.4196,1.470419e+05,7.569733e+13,2.396773e+08,3.916533e+09,758.88,12400.753676,202639.009754,2.016235e+18,6.383920e+12,1.043188e+14,20213136.0,3.303001e+08,5.397388e+09,64.0,1045.815195,17089.522223,279257.531513,6.178347e+36,1.858692e+29,4.950715e+33,1.567524e+28,2.561469e+29,5.591681e+21,1.489371e+26,4.715734e+20,7.705915e+21,3.967013e+30,1.256058e+25,2.052508e+26,3.977005e+19,6.498769e+20,1.061955e+22,1.682199e+14,4.480619e+18,1.418680e+13,2.318245e+14,1.193435e+23,3.778722e+17,6.174757e+18,1.196441e+12,1.955087e+13,3.194781e+14,3.178771e+27,1.006481e+22,1.644676e+23,3.186778e+16,5.207470e+17,8.509454e+18,1.009016e+11,1.648819e+12,2.694313e+13,4.402739e+14,5.060722e+06,1.347948e+11,4.267950e+05,6.974199e+06,3.590324e+15,1.136789e+10,1.857612e+11,35993.6784,5.881677e+05,9.611168e+06,9.563003e+19,3.027893e+14,4.947839e+15,9.587090e+08,1.566613e+10,2.559981e+11,3035.52,49603.014702,8.105560e+05,1.324518e+07,2.547152e+24,8.064940e+18,1.317881e+20,2.553568e+13,4.172750e+14,6.818634e+15,80852544.0,1.321200e+09,2.158955e+10,3.527919e+11,256.0,4183.260780,68358.088890,1.117030e+06,1.825324e+07
2,1.548114e+09,1.33,28425.0,6.0,24.413415,2.396657e+18,2.058992e+09,4.400514e+13,9.288684e+09,3.779475e+10,1.7689,37805.25,7.98,32.469843,8.079806e+08,170550.0,6.939513e+05,36.0,146.480493,596.014855,3.710299e+27,3.187554e+18,6.812498e+22,1.437994e+19,5.851059e+19,2.738459e+09,5.852684e+13,1.235395e+10,5.026702e+10,1.250846e+18,2.640309e+14,1.074316e+15,5.573211e+10,2.267685e+11,9.226990e+11,2.352637e+00,5.028098e+04,10.6134,4.318489e+01,1.074614e+09,2.268315e+05,9.229553e+05,47.88,194.819055,792.699757,2.296685e+13,4.847884e+09,1.972557e+10,1023300.0,4.163708e+06,1.694172e+07,216.0,878.882957,3576.089129,14550.758277,5.743966e+36,4.934697e+27,1.054652e+32,2.226179e+28,9.058106e+28,4.239447e+18,9.060622e+22,1.912532e+19,7.781908e+19,1.936453e+27,4.087499e+23,1.663163e+24,8.627966e+19,3.510635e+20,1.428443e+21,3.642150e+09,7.784070e+13,1.643075e+10,6.685514e+10,1.663625e+18,3.511610e+14,1.428840e+15,7.412370e+10,3.016021e+11,1.227190e+12,3.555530e+22,7.505077e+18,3.053743e+19,1.584185e+15,6.445895e+15,2.622772e+16,3.343926e+11,1.360611e+12,5.536194e+12,2.252623e+13,3.129007e+00,6.687371e+04,1.411582e+01,5.743590e+01,1.429237e+09,3.016859e+05,1.227531e+06,63.6804,2.591093e+02,1.054291e+03,3.054591e+13,6.447685e+09,2.623500e+10,1.360989e+06,5.537732e+06,2.253249e+07,287.28,1168.914333,4.756199e+03,1.935251e+04,6.528327e+17,1.378011e+14,5.606992e+14,2.908730e+10,1.183534e+11,4.815685e+11,6139800.0,2.498225e+07,1.016503e+08,4.136053e+08,1296.0,5273.297741,21456.534775,8.730455e+04,3.552337e+05
3,1.579858e+09,55.81,602.0,3.0,70.318960,2.495952e+18,8.817189e+10,9.510747e+11,4.739575e+09,1.110940e+11,3114.7561,33597.62,167.43,3924.501136,3.624040e+05,1806.0,4.233201e+04,9.0,210.956879,4944.756082,3.943250e+27,1.392991e+20,1.502563e+21,7.487856e+18,1.755128e+20,4.920873e+12,5.307948e+13,2.645157e+11,6.200155e+12,5.725469e+14,2.853224e+12,6.687858e+13,1.421872e+10,3.332820e+11,7.812014e+12,1.738345e+05,1.875083e+06,9344.2683,2.190264e+05,2.022577e+07,1.007929e+05,2.362550e+06,502.29,11773.503409,275966.836913,2.181672e+08,1.087212e+06,2.548387e+07,5418.0,1.269960e+05,2.976743e+06,27.0,632.870637,14834.268245,347710.103215,6.229777e+36,2.200728e+29,2.373837e+30,1.182975e+28,2.772853e+29,7.774282e+21,8.385805e+22,4.178973e+20,9.795367e+21,9.045430e+23,4.507689e+21,1.056587e+23,2.246357e+19,5.265383e+20,1.234187e+22,2.746339e+14,2.962366e+15,1.476262e+13,3.460307e+14,3.195385e+16,1.592384e+14,3.732494e+15,7.935470e+11,1.860047e+13,4.359885e+14,3.446733e+17,1.717641e+15,4.026091e+16,8.559672e+12,2.006357e+14,4.702832e+15,4.265617e+10,9.998459e+11,2.343604e+13,5.493327e+14,9.701706e+06,1.046484e+08,5.215036e+05,1.222386e+07,1.128800e+09,5.625250e+06,1.318539e+08,28032.8049,6.570792e+05,1.540171e+07,1.217591e+10,6.067730e+07,1.422255e+09,3.023786e+05,7.087649e+06,1.661320e+08,1506.87,35320.510226,8.279005e+05,1.940570e+07,1.313367e+11,6.545016e+08,1.534129e+10,3.261636e+06,7.645162e+07,1.791999e+09,16254.0,3.809881e+05,8.930229e+06,2.093215e+08,81.0,1898.611910,44502.804734,1.043130e+06,2.445061e+07
4,1.582526e+09,107.55,4664.0,6.0,59.356605,2.504390e+18,1.702007e+11,7.380904e+12,9.495159e+09,9.393340e+10,11567.0025,501613.20,645.30,6383.802875,2.175290e+07,27984.0,2.768392e+05,36.0,356.139630,3523.206565,3.963264e+27,2.693472e+20,1.168048e+22,1.502634e+19,1.486521e+20,1.830509e+13,7.938162e+14,1.021204e+12,1.010254e+13,3.442453e+16,4.428542e+13,4.381054e+14,5.697095e+10,5.636004e+11,5.575568e+12,1.244031e+06,5.394850e+07,69402.0150,6.865780e+05,2.339524e+09,3.009679e+06,2.977406e+07,3871.80,38302.817248,378920.866049,1.014555e+11,1.305174e+08,1.291178e+09,167904.0,1.661035e+06,1.643224e+07,216.0,2136.837782,21139.239389,209125.580632,6.271970e+36,4.262490e+29,1.848466e+31,2.377958e+28,2.352459e+29,2.896829e+22,1.256235e+24,1.616083e+21,1.598753e+22,5.447774e+25,7.008285e+22,6.933134e+23,9.015804e+19,8.919126e+20,8.823484e+21,1.968712e+15,8.537493e+16,1.098305e+14,1.086528e+15,3.702359e+18,4.762897e+15,4.711823e+16,6.127226e+12,6.061522e+13,5.996523e+14,1.605560e+20,2.065472e+17,2.043323e+18,2.657125e+14,2.628632e+15,2.600445e+16,3.418257e+11,3.381602e+12,3.345341e+13,3.309468e+14,1.337955e+08,5.802161e+09,7.464187e+06,7.384146e+07,2.516158e+11,3.236910e+08,3.202200e+09,416412.0900,4.119468e+06,4.075294e+07,1.091154e+13,1.403714e+10,1.388662e+11,1.805808e+07,1.786443e+08,1.767287e+09,23230.80,229816.903491,2.273525e+06,2.249146e+07,4.731885e+14,6.087330e+11,6.022054e+12,7.831043e+08,7.747068e+09,7.663995e+10,1007424.0,9.966211e+06,9.859341e+07,9.753617e+08,1296.0,12821.026694,126835.436334,1.254753e+06,1.241298e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
972501,1.576169e+09,7.11,338.0,4.0,36.279261,2.484310e+18,1.120657e+10,5.327453e+11,6.304678e+09,5.718226e+10,50.5521,2403.18,28.44,257.945544,1.142440e+05,1352.0,1.226239e+04,16.0,145.117043,1316.184763,3.915694e+27,1.766345e+19,8.396969e+20,9.937241e+18,9.012894e+19,7.967868e+10,3.787819e+12,4.482626e+10,4.065659e+11,1.800679e+14,2.130981e+12,1.932761e+13,2.521871e+10,2.287291e+11,2.074530e+12,3.594254e+02,1.708661e+04,202.2084,1.833993e+03,8.122748e+05,9.612720e+03,8.718559e+04,113.76,1031.782177,9358.073663,3.861447e+07,4.569760e+05,4.144688e+06,5408.0,4.904956e+04,4.448704e+05,64.0,580.468172,5264.739051,47750.210243,6.171798e+36,2.784058e+28,1.323505e+30,1.566278e+28,1.420585e+29,1.255871e+20,5.970245e+21,7.065378e+19,6.408168e+20,2.838175e+23,3.358787e+21,3.046358e+22,3.974896e+19,3.605158e+20,3.269811e+21,5.665154e+11,2.693139e+13,3.187147e+11,2.890684e+12,1.280283e+15,1.515128e+13,1.374193e+14,1.793050e+11,1.626264e+12,1.474991e+13,6.086295e+16,7.202716e+14,6.532731e+15,8.523925e+12,7.731042e+13,7.011912e+14,1.008748e+11,9.149162e+11,8.298121e+12,7.526242e+13,2.555515e+03,1.214858e+05,1.437702e+03,1.303969e+04,5.775274e+06,6.834644e+04,6.198896e+05,808.8336,7.335971e+03,6.653590e+04,2.745489e+08,3.249099e+06,2.946873e+07,3.845088e+04,3.487424e+05,3.163029e+06,455.04,4127.128706,3.743229e+04,3.395040e+05,1.305169e+10,1.544579e+08,1.400904e+09,1.827904e+06,1.657875e+07,1.503662e+08,21632.0,1.961982e+05,1.779482e+06,1.613957e+07,256.0,2321.872690,21058.956204,1.910008e+05,1.732342e+06
972502,1.564789e+09,38.55,213.0,4.0,52.728268,2.448565e+18,6.032262e+10,3.333001e+11,6.259157e+09,8.250863e+10,1486.1025,8211.15,154.20,2032.674743,4.536900e+04,852.0,1.123112e+04,16.0,210.913073,2780.270279,3.831489e+27,9.439219e+19,5.215444e+20,9.794261e+18,1.291086e+20,2.325437e+12,1.284872e+13,2.412905e+11,3.180708e+12,7.099292e+13,1.333200e+12,1.757434e+13,2.503663e+10,3.300345e+11,4.350537e+12,5.728925e+04,3.165398e+05,5944.4100,7.835961e+04,1.748975e+06,3.284460e+04,4.329597e+05,616.80,8130.698973,107179.419252,9.663597e+06,1.814760e+05,2.392229e+06,3408.0,4.492448e+04,5.921976e+05,64.0,843.652293,11121.081116,146598.837239,5.995472e+36,1.477039e+29,8.161071e+29,1.532595e+28,2.020278e+29,3.638819e+21,2.010554e+22,3.775688e+20,4.977137e+21,1.110890e+23,2.086178e+21,2.750013e+22,3.917705e+19,5.164344e+20,6.807673e+21,8.964560e+13,4.953181e+14,9.301749e+12,1.226163e+14,2.736777e+15,5.139488e+13,6.774907e+14,9.651620e+11,1.272283e+13,1.677132e+14,1.512149e+16,2.839717e+14,3.743334e+15,5.332802e+12,7.029735e+13,9.266644e+14,1.001465e+11,1.320138e+12,1.740215e+13,2.293963e+14,2.208501e+06,1.220261e+07,2.291570e+05,3.020763e+06,6.742298e+07,1.266159e+06,1.669060e+07,23777.6400,3.134384e+05,4.131767e+06,3.725317e+08,6.995900e+06,9.222042e+07,1.313784e+05,1.731839e+06,2.282922e+07,2467.20,32522.795893,4.287177e+05,5.651385e+06,2.058346e+09,3.865439e+07,5.095447e+08,7.259040e+05,9.568915e+06,1.261381e+08,13632.0,1.796979e+05,2.368790e+06,3.122555e+07,256.0,3374.609172,44484.324462,5.863953e+05,7.729903e+06
972503,1.564169e+09,173.39,3776.0,5.0,48.153320,2.446626e+18,2.712113e+11,5.906304e+12,7.820847e+09,7.531995e+10,30064.0921,654720.64,866.95,8349.304093,1.425818e+07,18880.0,1.818269e+05,25.0,240.766598,2318.742193,3.826937e+27,4.242205e+20,9.238459e+21,1.223313e+19,1.178132e+20,4.702533e+13,1.024094e+15,1.356057e+12,1.305973e+13,2.230220e+16,2.953152e+13,2.844081e+14,3.910424e+10,3.765997e+11,3.626906e+12,5.212813e+06,1.135220e+08,150320.4605,1.447686e+06,2.472225e+09,3.273603e+06,3.152697e+07,4334.75,41746.520465,402046.708800,5.383887e+10,7.129088e+07,6.865785e+08,94400.0,9.091347e+05,8.755571e+06,125.0,1203.832991,11593.710964,111655.133979,5.985978e+36,6.635527e+29,1.445052e+31,1.913469e+28,1.842797e+29,7.355559e+22,1.601856e+24,2.121102e+21,2.042762e+22,3.488442e+25,4.619230e+22,4.448625e+23,6.116565e+19,5.890658e+20,5.673095e+21,8.153722e+15,1.775677e+17,2.351267e+14,2.264426e+15,3.866979e+18,5.120470e+15,4.931353e+16,6.780283e+12,6.529863e+13,6.288692e+14,8.421312e+19,1.115110e+17,1.073925e+18,1.476576e+14,1.422041e+15,1.369520e+16,1.955212e+11,1.882999e+12,1.813453e+13,1.746475e+14,9.038496e+08,1.968358e+10,2.606406e+07,2.510142e+08,4.286591e+11,5.676101e+08,5.466462e+09,751602.3025,7.238429e+06,6.971088e+07,9.335122e+12,1.236113e+10,1.190458e+11,1.636802e+07,1.576349e+08,1.518128e+09,21673.75,208732.602327,2.010234e+06,1.935988e+07,2.032956e+14,2.691944e+11,2.592520e+12,3.564544e+08,3.432893e+09,3.306103e+10,472000.0,4.545673e+06,4.377785e+07,4.216098e+08,625.0,6019.164956,57968.554819,5.582757e+05,5.376565e+06
972504,1.564804e+09,124.90,754.0,3.0,62.488706,2.448611e+18,1.954440e+11,1.179862e+12,4.694412e+09,9.778257e+10,15600.0100,94174.60,374.70,7804.839425,5.685160e+05,2262.0,4.711648e+04,9.0,187.466119,3904.838423,3.831597e+27,3.058316e+20,1.846253e+21,7.345834e+18,1.530106e+20,2.441096e+13,1.473648e+14,5.863320e+11,1.221304e+13,8.896161e+14,3.539586e+12,7.372806e+13,1.408324e+10,2.933477e+11,6.110306e+12,1.948441e+06,1.176241e+07,46800.0300,9.748244e+05,7.100765e+07,2.825238e+05,5.884849e+06,1124.10,23414.518275,487714.319062,4.286611e+08,1.705548e+06,3.552583e+07,6786.0,1.413495e+05,2.944248e+06,27.0,562.398357,11714.515270,244008.301634,5.995697e+36,4.785664e+29,2.889024e+30,1.149479e+28,2.394315e+29,3.819836e+22,2.305970e+23,9.174947e+20,1.911102e+22,1.392075e+24,5.538759e+21,1.153700e+23,2.203750e+19,4.590317e+20,9.561432e+21,3.048929e+15,1.840586e+16,7.323287e+13,1.525409e+15,1.111130e+17,4.420944e+14,9.208635e+15,1.758996e+12,3.663913e+13,7.631773e+14,6.707705e+17,2.668848e+15,5.559096e+16,1.061876e+13,2.211842e+14,4.607171e+15,4.224971e+10,8.800432e+11,1.833092e+13,3.818251e+14,2.433603e+08,1.469125e+09,5.845324e+06,1.217556e+08,8.868855e+09,3.528722e+07,7.350176e+08,140400.0900,2.924473e+06,6.091552e+07,5.353977e+10,2.130229e+08,4.437176e+09,8.475714e+05,1.765455e+07,3.677366e+08,3372.30,70243.554825,1.463143e+06,3.047664e+07,3.232104e+11,1.285983e+09,2.678648e+10,5.116644e+06,1.065775e+08,2.219963e+09,20358.0,4.240484e+05,8.832745e+06,1.839823e+08,81.0,1687.195072,35143.545809,7.320249e+05,1.524776e+07
972505,1.552325e+09,4.08,2504700.0,2.0,25.185489,2.409713e+18,6.333486e+09,3.888108e+15,3.104650e+09,3.909606e+10,16.6464,10219176.00,8.16,102.756797,6.273522e+12,5009400.0,6.308210e+07,4.0,50.370979,634.308876,3.740657e+27,9.831628e+18,6.035607e+24,4.819425e+18,6.068979e+19,2.584062e+10,1.586348e+16,1.266697e+10,1.595119e+11,9.738545e+21,7.776217e+15,9.792391e+16,6.209300e+09,7.819213e+10,9.846535e+11,6.791731e+01,4.169424e+07,33.2928,4.192477e+02,2.559597e+13,2.043835e+07,2.573749e+08,16.32,205.513593,2587.980213,1.571329e+19,1.254704e+13,1.580017e+14,10018800.0,1.261642e+08,1.588753e+09,8.0,100.741958,1268.617752,15975.379463,5.806715e+36,1.526188e+28,9.369224e+33,7.481314e+27,9.421028e+28,4.011304e+19,2.462528e+25,1.966326e+19,2.476144e+20,1.511739e+31,1.207121e+25,1.520097e+26,9.638851e+18,1.213796e+20,1.528502e+21,1.054297e+11,6.472301e+16,5.168124e+10,6.508087e+11,3.973326e+22,3.172696e+16,3.995296e+17,2.533394e+10,3.190239e+11,4.017386e+12,2.439213e+28,1.947709e+22,2.452700e+23,1.555243e+16,1.958478e+17,2.466262e+18,1.241860e+10,1.563843e+11,1.969307e+12,2.479898e+13,2.771026e+02,1.701125e+08,1.358346e+02,1.710531e+03,1.044316e+14,8.338848e+07,1.050090e+09,66.5856,8.384955e+02,1.055896e+04,6.411023e+19,5.119194e+13,6.446470e+14,4.087670e+07,5.147499e+08,6.482114e+09,32.64,411.027187,5.175960e+03,6.517955e+04,3.935708e+25,3.142658e+19,3.957469e+20,2.509409e+13,3.160034e+14,3.979351e+15,20037600.0,2.523284e+08,3.177507e+09,4.001353e+10,16.0,201.483915,2537.235503,3.195076e+04,4.023477e+05

In [15]:
import sys
print(sys.getsizeof(X_train_num))

972506164

In [23]:
def evaluate(X, y):
    models = dict()
    
    models['Logistic Regression'] = LogisticRegression(random_state=1, max_iter=100000, class_weight='balanced')    
    #models['SVC'] = SVC(class_weight='balanced', random_state=1)
    models['SGD'] = SGDClassifier(random_state=1, class_weight='balanced')
    models['Nearest Neighbor'] = KNeighborsClassifier(3)
    models['Naive Bayes'] = GaussianNB()
    models['Decision Tree'] = DecisionTreeClassifier(random_state=1, class_weight='balanced')
    models['Random Forest'] = RandomForestClassifier(random_state=1, class_weight='balanced')
    models['MLPC'] = MLPClassifier(random_state=1)

    cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=10, random_state=1)
    
    names, res = [], []

    for name, model in models.items():
        print('         ', name)
        scores = cross_val_score(model, X, y, scoring='f1_score', cv=cv, n_jobs=10)#scoring='accuracy'
        print('Min:', min(scores), 'Max:', max(scores), 'Mean:', np.mean(scores))
        res.append(scores)
        names.append(name)

    plt.figure(figsize=(10, 8))
    plt.boxplot(res, labels=names, showmeans=True)
    plt.grid()
    plt.xticks(rotation=25);

### Feature selection

In [17]:
X_train_num = pd.DataFrame(StandardScaler().fit_transform(X_train_num), columns=X_train_num.columns)

In [19]:
enc = OneHotEncoder(drop='first', sparse_output=False, dtype=bool)
X_train_cat = pd.DataFrame(enc.fit_transform(X_train_cat), columns=enc.get_feature_names_out())

In [21]:
X_train = pd.concat([X_train_num, X_train_cat], axis=1)

In [22]:
X_train

,time,amount,city_pop,industry_code,age,time^2,time amount,time city_pop,time industry_code,time age,amount^2,amount city_pop,amount industry_code,amount age,city_pop^2,city_pop industry_code,city_pop age,industry_code^2,industry_code age,age^2,time^3,time^2 amount,time^2 city_pop,time^2 industry_code,time^2 age,time amount^2,time amount city_pop,time amount industry_code,time amount age,time city_pop^2,time city_pop industry_code,time city_pop age,time industry_code^2,time industry_code age,time age^2,amount^3,amount^2 city_pop,amount^2 industry_code,amount^2 age,amount city_pop^2,amount city_pop industry_code,amount city_pop age,amount industry_code^2,amount industry_code age,amount age^2,city_pop^3,city_pop^2 industry_code,city_pop^2 age,city_pop industry_code^2,city_pop industry_code age,city_pop age^2,industry_code^3,industry_code^2 age,industry_code age^2,age^3,time^4,time^3 amount,time^3 city_pop,time^3 industry_code,time^3 age,time^2 amount^2,time^2 amount city_pop,time^2 amount industry_code,time^2 amount age,time^2 city_pop^2,time^2 city_pop industry_code,time^2 city_pop age,time^2 industry_code^2,time^2 industry_code age,time^2 age^2,time amount^3,time amount^2 city_pop,time amount^2 industry_code,time amount^2 age,time amount city_pop^2,time amount city_pop industry_code,time amount city_pop age,time amount industry_code^2,time amount industry_code age,time amount age^2,time city_pop^3,time city_pop^2 industry_code,time city_pop^2 age,time city_pop industry_code^2,time city_pop industry_code age,time city_pop age^2,time industry_code^3,time industry_code^2 age,time industry_code age^2,time age^3,amount^4,amount^3 city_pop,amount^3 industry_code,amount^3 age,amount^2 city_pop^2,amount^2 city_pop industry_code,amount^2 city_pop age,amount^2 industry_code^2,amount^2 industry_code age,amount^2 age^2,amount city_pop^3,amount city_pop^2 industry_code,amount city_pop^2 age,amount city_pop industry_code^2,amount city_pop industry_code age,amount city_pop age^2,amount industry_code^3,amount industry_code^2 age,amount industry_code age^2,amount age^3,city_pop^4,city_pop^3 industry_code,city_pop^3 age,city_pop^2 industry_code^2,city_pop^2 industry_code age,city_pop^2 age^2,city_pop industry_code^3,city_pop industry_code^2 age,city_pop industry_code age^2,city_pop age^3,industry_code^4,industry_code^3 age,industry_code^2 age^2,industry_code age^3,age^4,category_food_dining,category_gas_transport,category_grocery_net,category_grocery_pos,category_health_fitness,category_home,category_kids_pets,category_misc_net,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel,gender_M,state_AL,state_AR,state_AZ,state_CA,state_CO,state_CT,state_DC,state_DE,state_FL,state_GA,state_HI,state_IA,state_ID,state_IL,state_IN,state_KS,state_KY,state_LA,state_MA,state_MD,state_ME,state_MI,state_MN,state_MO,state_MS,state_MT,state_NC,state_ND,state_NE,state_NH,state_NJ,state_NM,state_NV,state_NY,state_OH,state_OK,state_OR,state_PA,state_RI,state_SC,state_SD,state_TN,state_TX,state_UT,state_VA,state_VT,state_WA,state_WI,state_WV,state_WY
0,-1.259216,-0.054417,-0.287405,0.305652,-1.758199,-1.256755,-0.058295,-0.287477,0.271422,-1.769877,-0.014371,-0.109573,-0.013482,-0.250204,-0.159566,-0.264749,-0.297210,0.142090,-1.143290,-1.248641,-1.254265,-0.062148,-0.287529,0.237188,-1.780357,-0.014362,-0.109515,-0.017295,-0.251296,-0.159569,-0.264830,-0.297245,0.124828,-1.152427,-1.250697,-0.004288,-0.007293,-0.011525,-0.012702,-0.067848,-0.110532,-0.115024,-0.013604,-0.208525,-0.275079,-0.112223,-0.140531,-0.166813,-0.231840,-0.264230,-0.282982,-0.007271,-0.741264,-1.064964,-0.915204,-1.251748,-0.065976,-0.287559,0.203023,-1.789623,-0.014352,-0.109455,-0.021082,-0.252362,-0.159561,-0.264891,-0.297257,0.107614,-1.161121,-1.252481,-0.004282,-0.007280,-0.011506,-0.012670,-0.067805,-0.110489,-0.114928,-0.016729,-0.209496,-0.275073,-0.112226,-0.140537,-0.166819,-0.231911,-0.264264,-0.282992,-0.017697,-0.747141,-1.066934,-0.915617,-0.002929,-0.002515,-0.003789,-0.003734,-0.005437,-0.010058,-0.008967,-0.009260,-0.010464,-0.010421,-0.051903,-0.064338,-0.070478,-0.101426,-0.108614,-0.108297,-0.033980,-0.174758,-0.242300,-0.239927,-0.090061,-0.098241,-0.115203,-0.122084,-0.143056,-0.166874,-0.204430,-0.226386,-0.248493,-0.254953,-0.125255,-0.563698,-0.831936,-0.835977,-0.701427,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,0.503967,-0.141437,3.882829,0.305652,0.819782,0.500887,-0.140150,3.900315,0.319235,0.835113,-0.015175,0.909034,-0.098749,-0.051202,2.402762,4.035715,5.801228,0.142090,0.835580,0.680329,0.497781,-0.138869,3.917305,0.332419,0.849701,-0.015139,0.912650,-0.097451,-0.049758,2.413620,4.053854,5.826834,0.148993,0.847388,0.689137,-0.004290,-0.000588,-0.012206,-0.012145,0.614070,1.023926,1.378570,-0.083812,-0.014973,0.001117,1.147897,2.338956,3.912165,3.494034,5.640463,7.239754,-0.007271,0.522127,0.776240,0.504733,0.494650,-0.137595,3.933792,0.345176,0.863517,-0.015102,0.916179,-0.096163,-0.048332,2.424184,4.071486,5.851707,0.155776,0.858749,0.697690,-0.004284,-0.000560,-0.012163,-0.012104,0.616480,1.028050,1.383555,-0.082688,-0.013606,0.002415,1.153279,2.349560,3.929559,3.509756,5.665286,7.271239,-0.003085,0.529702,0.784634,0.510783,-0.002929,-0.002493,-0.003791,-0.003733,0.000159,0.000867,0.002972,-0.009774,-0.009986,-0.009555,0.303299,0.626953,0.986116,0.919113,1.417258,1.707452,-0.086059,-0.014892,0.029477,0.013290,0.486558,1.070289,1.948357,1.987391,3.556235,5.531588,2.750272,4.654923,6.836499,7.826360,-0.125255,0.251936,0.593316,0.597291,0.329303,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
2,-1.710481,-0.425346,-0.200474,1.961812,-1.533377,-1.702509,-0.425205,-0.201786,1.891650,-1.552611,-0.016349,-0.111168,-0.372926,-0.383320,-0.158276,-0.126642,-0.249167,2.234258,-0.432281,-1.160647,-1.694552,-0.425031,-0.203070,1.820958,-1.570643,-0.016314,-0.111095,-0.372636,-0.382884,-0.158297,-0.128672,-0.249883,2.181318,-0.454816,-1.164718,-0.004293,-0.007312,-0.013199,-0.013326,-0.067841,-0.111950,-0.115700,-0.304610,-0.336286,-0.314267,-0.112209,-0.138655,-0.166045,-0.049204,-0.192888,-0.260616,2.396273,0.228311,-0.838532,-0.884069,-1.686610,-0.424825,-0.204327,1.749884,-1.587442,-0.016278,-0.111019,-0.372318,-0.382422,-0.158307,-0.130674,-0.250574,2.128404,-0.476968,-1.168506,-0.004287,-0.007299,-0.013156,-0.013285,-0.067797,-0.111896,-0.115598,-0.304256,-0.335714,-0.313802,-0.112212,-0.138687,-0.166062,-0.051841,-0.193928,-0.260943,2.348321,0.206645,-0.844433,-0.885086,-0.002929,-0.002515,-0.003793,-0.003735,-0.005437,-0.010088,-0.008977,-0.010524,-0.011000,-0.010593,-0.051903,-0.064326,-0.070473,-0.102217,-0.109125,-0.108529,-0.244329,-0.278165,-0.280252,-0.250106,-0.090061,-0.098221,-0.115194,-0.119687,-0.142010,-0.166473,0.015323,-0.136626,-0.216307,-0.245900,2.492474,0.561588,-0.491267,-0.766021,-0.691244,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
3,0.758343,-0.089828,-0.292474,-0.522428,1.104546,0.756565,-0.087644,-0.292462,-0.506837,1.129398,-0.014724,-0.111239,-0.132376,0.038040,-0.159572,-0.270490,-0.297316,-0.590169,0.278729,1.017027,0.754753,-0.085467,-0.292428,-0.490998,1.153378,-0.014683,-0.111155,-0.130649,0.040621,-0.159575,-0.270486,-0.297298,-0.584259,0.293162,1.032359,-0.004289,-0.007308,-0.012168,-0.011567,-0.067851,-0.112548,-0.115151,-0.163495,-0.031485,0.115692,-0.112223,-0.140538,-0.166816,-0.237147,-0.265090,-0.280084,-0.592344,-0.204693,0.506751,0.863874,0.752906,-0.083297,-0.292373,-0.474947,1.176439,-0.014642,-0.111066,-0.128925,0.043181,-0.159568,-0.270463,-0.297258,-0.578250,0.307417,1.047397,-0.004283,-0.007294,-0.012122,-0.011522,-0.067807,-0.112475,-0.115039,-0.162227,-0.029509,0.118181,-0.112226,-0.140544,-0.166822,-0.237147,-0.265078,-0.280055,-0.589654,-0.197741,0.517745,0.875194,-0.002929,-0.002515,-0.003791,-0.003732,-0.005437,-0.010083,-0.008969,-0.009940,-0.009867,-0.008930,-0.051903,-0.064340,-0.070479,-0.103347,-0.108974,-0.107511,-0.174094,-0.092528,0.036144,0.135979,-0.090061,-0.098241,-0.115203,-0.122090,-0.143059,-0.166874,-0.208836,-0.227566,-0.246740,-0.250579,-0.565738,-0.397075,0.041671,0.499451,0.682679,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,0.965860,0.228815,-0.279043,1.961812,0.474604,0.965536,0.233907,-0.278920,2.000512,0.501494,-0.010312,-0.103266,0.588550,0.304289,-0.159538,-0.248174,-0.279988,2.234258,1.879723,0.305173,0.965176,0.238971,-0.278777,2.037793,0.528013,-0.010245,-0.103122,0.595507,0.309354,-0.159541,-0.247989,-0.279826,2.263848,1.910546,0.319132,-0.004266,-0.007185,-0.005531,-0.007812,-0.067830,-0.098749,-0.104690,0.882893,0.666881,0.276557,-0.112223,-0.140487,-0.166766,-0.207146,-0.237652,-0.261327,2.396273,2.442425,1.260157,0.136781,0.964780,0.244005,-0.278613,2.073582,0.554108,-0.010178,-0.102975,0.602396,0.314381,-0.159533,-0.247787,-0.279644,2.292900,1.940667,0.333010,-0.004260,-0.007170,-0.005458,-0.007749,-0.067786,-0.098574,-0.104503,0.890748,0.673546,0.280798,-0.112226,-0.140493,-0.166772,-0.206904,-0.237417,-0.261141,2.423177,2.472003,1.280066,0.145475,-0.002929,-0.002514,-0.003760,-0.003712,-0.005437,-0.009777,-0.008771,-0.001838,-0.003896,-0.006192,-0.051903,-0.064308,-0.070449,-0.084404,-0.092253,-0.096152,1.076975,0.964697,0.591806,0.197432,-0.090061,-0.098241,-0.115203,-0.122025,-0.142991,-0.166812,-0.172553,-0.192134,-0.217310,-0.233031,2.492474,2.705708,1.945585,0.779631,-0.003709,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
972501,0.471459,-0.389750,-0.293347,0.305652,-0.851516,0.468251,-0.389347,-0.293343,0.318353,-0.843225,-0.016323,-0.111771,-0.342060,-0.358909,-0.159573,-0.270877,-0.299538,0.142090,-0.447316,-0.800015,0.465018,-0.388918,-0.293317,0.330650,-0.834511,-0.016288,-0.111689,-0.341474,-0.358348,-0.159576,-0.270878,-0.299536,0.148548,-0.441048,-0.797387,-0.004293,-0.007312,-0.013178,-0.013311,-0.067851,-0.112981,-0.116019,-0.284151,-0.314253,-0.300884,-0.112223,-0.140538,-0.166817,-0.237149,-0.266484,-0.283613,-0.007271,-0.296926,-0.636749,-0.709886,0.461761,-0.388462,-0.293270,0.342518,-0.825394,-0.016253,-0.111604,-0.340867,-0.357764,-0.159568,-0.270860,-0.299512,0.154882,-0.434716,-0.794628,-0.004287,-0.007299,-0.013135,-0.013270,-0.067807,-0.112910,-0.115912,-0.283491,-0.313548,-0.300365,-0.112226,-0.140544,-0.166823,-0.237151,-0.266483,-0.283608,-0.003355,-0.292940,-0.634250,-0.708872,-0.002929,-0.002515,-0.003793,-0.003735,-0.005437,-0.010089,-0.008977,-0.010508,-0.010987,-0.010586,-0.051903,-0.064340,-0.070479,-0.103628,-0.109631,-0.108667,-0.234668,-0.262086,-0.267692,-0.243730,-0.090061,-0.098241,-0.115203,-0.122090,-0.143059,-0.166875,-0.208640,-0.228249,-0.249087,-0.255005,-0.125255,-0.276837,-0.500460,-0.628731,-0.612721,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
972502,-0.413612,-0.196125,-0.293760,0.305652,0.093712,-0.416985,-0.196813,-0.293763,0.294353,0.083463,-0.015574,-0.111672,-0.152335,-0.166773,-0.159573,-0.271303,-0.299615,0.142090,0.278246,-0.066860,-0.420335,-0.197499,-0.293744,0.282688,0.073006,-0.015543,-0.111591,-0.152937,-0.167310,-0.159576,-0.271312,-0.299619,0.136418,0.270357,-0.071543,-0.004292,-0.007312,-0.012543,-0.012697,-0.067851,-0.112871,-0.115887,-0.127934,-0.127379,-0.148038,-0.112223,-0.140538,-0.166817,-0.237518,-0.266558,-0.283408,-0.007271,0.166302,0.063048,-0.191270,-0.423662,-0.198181,-0.293703,0.270685,0.062362,-0.015513,-0.111506,-0.153539,-0.167845,-0.159568,-0.271301,-0.299601,0.130625,0.262252,-0.076287,-0.004285,-0.007298,-0.012505,-0.012660,-0.067807,-0.112801,-0.115781,-0.128347,-0.127863,-0.148380,-0.112226,-0.140544,-0.166823,-0.237526,-0.266563,-0.283408,-0.010689,0.161279,0.058566,-0.193847,-0.002929,-0.002515,-0.003792,-0.003734,-0.005437,-0.010088,-0.008976,-0.010029,-0.010459,-0.010147,-0.051903,-0.064340,-0.070479,-0.103529,-0.109496,-0.108527,-0.118789,-0.107735,-0.117292,-0.137942,-0.090061,-0.098241,-0.115203,-0.122090,-0.143059,-0.166875,-0.208932,-0.228310,-0.248893,-0.254659,-0.125255,0.022219,0.041243,-0.105246,-0.270739,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
972503,-0.461818,0.634293,-0.281979,1.133732,-0.169183,-0.465016,0.629866,-0.282025,1.117743,-0.179569,-0.000656,-0.100657,0.922936,0.517079,-0.159550,-0.255935,-0.287009,1.083566,0.607454,-0.297974,-0.468188,0.625341,-0.282052,1.100808,-0.189972,-0.000722,-0.100625,0.916848,0.512998,-0.159553,-0.256000,-0.287060,1.073587,0.597356,-0.302317,-0.004181,-0.007044,0.003412,-0.001699,-0.067828,-0.097497,-0.104021,1.026660,0.757534,0.312691,-0.112223,-0.140510,-0.166790,-0.220718,-0.251100,-0.272028,0.957309,0.800252,0.119524,-0.374604,-0.471336,0.620721,-0.282059,1.082969,-0.200371,-0.000788,-0.100590,0.910639,0.508845,-0.159545,-0.256048,-0.287091,1.063235,0.586919,-0.306656,-0.004176,-0.007032,0.003326,-0.001747,-0.067785,-0.097494,-0.103970,1.019675,0.751916,0.309828,-0.112226,-0.140516,-0.166796,-0.220788,-0.251163,-0.272071,0.949795,0.792197,0.114300,-0.376785,-0.002928,-0.002512,-0.003679,-0.003656,-0.005437,-0.009542,-0.008626,0.005155,0.001483,-0.003065,-0.051903,-0.064312,-0.070454,-0.086207,-0.094301,-0.097919,0.987306,0.850089,0.490604,0.135066,-0.090061,-0.098241,-0.115203,-0.122061,-0.143029,-0.166848,-0.192153,-0.212171,-0.235302,-0.245716,0.803536,0.773471,0.353062,-0.142476,-0.404927,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
972504,-0.412469,0.335665,-0.291971,-0.522428,0.654587,-0.415846,0.332860,-0.291980,-0.530648,0.642335,-0.008206,-0.110207,0.180316,0.458134,-0.159572,-0.270101,-0.296963,-0.590169,0.019686,0.496278,-0.419200,0.329990,-0.291967,-0.538639,0.629486,-0.008220,-0.110132,0.178182,0.454692,-0.159575,-0.270114,-0.296976,-0.593286,0.012729,0.489666,-0.004251,-0.007285,-0.008028,-0.005497,-0.067850,-0.111686,-0.113806,0.029606,0.274957,0.446546,-0.112223,-0.140537,-0.166815,-0.236895,-0.264833,-0.280129,-0.592344,-0.328730,0.133960,0.319796,-0.422531,0.327058,-0.291933,-0.546384,0.616070,-0.008234,-0.110053,0.176008,0.451181,-0.159567,-0.270107,-0.296967,-0.596320,0.005657,0.482846,-0.004245,-0.007271,-0.008023,-0.005513,-0.067806,-0.111621,-0.113709,0.028372,0.272341,0.443278,-0.112226,-0.140543,-0.166822,-0.236905,-0.264844,-0.280140,-0.593748,-0.332030,0.129245,0.315481,-0.002928,-0.002515,-0.003767,-0.003697,-0.005437,-0.010055,-0.008930,-0.007596,-0.005957,-0.004014,-0.051903,-0.064340,-0.070478,-0.102765,-0.107944,-0.106080,-0.066664,0.097304,0.280316,0.356459,-0.090061,-0.098241,-0.115203,-0.122090,-0.143058,-0.166874,-0.208686,-0.227407,-0.246772,-0.251160,-0.565738,-0.457133,-0.174759,0.087561,0.157931,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
972505,-1.382992,-0.408410,7.987568,-1.350508,-1.489010,-1.379184,-0.408449,7.894249,-1.368839,-1.504997,-0.016341,0.062292,-0.372655,-0.375710,9.912523,3.998306,4.360848,-1.113211,-1.492122,-1.141470,-1.375357,-0.408456,7.800867,-1.386125,-1.519907,-0.016306,0.060288,-0.372336,-0.375361,9.799556,3.950293,4.308374,-1.117839,-1.498176,-1.144960,-0.004293,-0.007214,-0.013197,-0.013323,0.162731,-0.016073,-0.017833,-0.314411,-0.336004,-0.311462,9.708373,4.732695,6.011230,1.611737,1.989241,1.930497,-0.892787,-1.141287,-1.114261,-0.876595,-1.371510,-0.408431,7.707451,-1.402334,-1.533717,-0.016271,0.058296,-0.371990,-0.374985,9.686527,3.902260,4.255874,-1.122189,-1.503672,-1.148189,-0.004287,-0.007202,-0.013154,-0.013282,0.160014,-0.017155,-0.018922,-0.313888,-0.335422,-0.311029,9.598558,4.678224,5.942097,1.590939,1.963848,1.905542,-0.894166,-1.143189,-1.115873,-0.877492,-0.002929,-0.002515,-0.003793,-0.003735,-0.005275,-0.010008,-0.008910,-0.010524,-0.010999,-0.010592,0.186224,0.052535,0.067183,-0.060061,-0.059494,-0.062703,-0.258994,-0.282285,-0.280091,-0.249193,8.819515,4.455158,6.081469,1.950912,2.658426,3.158745,0.524069,0.703772,0.793257,0.661253,-0.729346,-0.879186,-0.928769,-0.839307,-0.688558,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [25]:
pca = PCA(n_components=0.99, copy=False)
X_train_num = pd.DataFrame(pca.fit_transform(X_train_num))
print(X_train_num.shape)
X_train_num.info()

(972506, 18)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 972506 entries, 0 to 972505
Data columns (total 18 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   0       972506 non-null  float64
 1   1       972506 non-null  float64
 2   2       972506 non-null  float64
 3   3       972506 non-null  float64
 4   4       972506 non-null  float64
 5   5       972506 non-null  float64
 6   6       972506 non-null  float64
 7   7       972506 non-null  float64
 8   8       972506 non-null  float64
 9   9       972506 non-null  float64
 10  10      972506 non-null  float64
 11  11      972506 non-null  float64
 12  12      972506 non-null  float64
 13  13      972506 non-null  float64
 14  14      972506 non-null  float64
 15  15      972506 non-null  float64
 16  16      972506 non-null  float64
 17  17      972506 non-null  float64
dtypes: float64(18)
memory usage: 133.6 MB

In [ ]:
ct = ColumnTransformer(
    [
        ("text_preprocess", OneHotEncoder(drop='first', sparse_output=False, dtype=bool), ['category', 'gender', 'state'])
    ],
    remainder='passthrough', verbose_feature_names_out=False).set_output(transform='pandas')

### Handling imbalanced data